### ISSUE TITLE
Systems manager URL has changed

### ISSUE THREAD

**Issue by dnorth98** [rkoval/alfred-aws-console-services-workflow#15]
Looks like the service URL for Systems Manager has changed from `systemsmanager` to `systems-manager`.

`systemsmanager` now gives a 404

**Comment by tsub** [comment]
@dnorth98 System Manager URL is fixed in PR https://github.com/rkoval/alfred-aws-console-services-workflow/pull/12.

Please download [v2.3](https://github.com/rkoval/alfred-aws-console-services-workflow/releases/tag/v2.3) and update installed workflow.

**Comment by dnorth98** [comment]
AH cool!  Yeah, I just installed from packal and it's still giving 2.2 as the download.  I'll grab 2.3 from here and install.

http://www.packal.org/workflow/aws-console-services

Thanks!
