### ISSUE TITLE
AWS China region support

### ISSUE THREAD

**Issue by eph6666** [rkoval/alfred-aws-console-services-workflow#32]
Will AWS China region be supported in future?

AWS China url example:
https://cn-northwest-1.console.amazonaws.cn/ec2/v2/home?region=cn-northwest-1#Home:

**Comment by rkoval** [comment]
as long as your region is set in your `~/.aws/config` directory per the [installation instructions](https://github.com/rkoval/alfred-aws-console-services-workflow#installation), this should just work. 

is this still not working even though that file is populated correctly?

**Comment by eph6666** [comment]
China region has different domain name. Such as ec2: https://cn-northwest-1.console.amazonaws.cn/ec2/v2/home?region=cn-northwest-1#Home
Domain is "amazonaws.cn"

**Comment by rkoval** [comment]
ahhh, sorry! i missed that. i can look into this. it doesn't actually seem like it should be too tough to implement

**Comment by rkoval** [comment]
i've just published [a new release](https://github.com/rkoval/alfred-aws-console-services-workflow/releases/tag/v4.1.0) that has support for regions in china. closing this issue in the meantime, but please let me know if this still does not resolve your issue
