### ISSUE TITLE
Add a Gitter Channel for chat and Add a release history file

### ISSUE THREAD

**Issue by MacHu-GWU** [rkoval/alfred-aws-console-services-workflow#41]
Hi Rkoval, 

1. Maybe you can create a Gitter channel and paste the badge in the README file for live chat. It is a free slack-liked message app for open source project. https://gitter.im/

2. I observed that you just added the aws profile switch features 3 days ago. As an open source project, you can create a Changelog.md or release-history.md file to track what's the new feature for each version.

**Comment by rkoval** [comment]
hey again @MacHu-GWU !

>    Maybe you can create a Gitter channel and paste the badge in the README file for live chat. It is a free slack-liked message app for open source project. https://gitter.im/

this is a good suggestion, though i don't think i will do this at this time. given that this project is not that big, and i'm more or less the sole maintainer, i'd like to not have to spend time managing/moderating a separate chat application. for anyone that requires support or feedback, i think github issues is accessible enough. i encourage anyone to use them for that purpose. if/when this need changes, i will re-evaluate

>    I observed that you just added the aws profile switch features 3 days ago. As an open source project, you can create a Changelog.md or release-history.md file to track what's the new feature for each version.

i currently maintain a change log for each release within the [releases page](https://github.com/rkoval/alfred-aws-console-services-workflow/releases) of this repository. you can check that for details of each release!
