### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by dustinlacewell** [rkoval/alfred-aws-console-services-workflow#47]
Anytime I type `aw` it looks like the aws workflow is going to be selected. But as soon as I have typed `aws` it dissapears and only web searches are available to select.

**Comment by rkoval** [comment]
hmm, is there anything in the workflow logs? Alfred Preferrences --> Workflows --> AWS Console Service --> click the bug icon in the top right. then, try to run the workflow again

**Comment by rkoval** [comment]
also, what macOS version are you running / hardware?

**Comment by dustinlacewell** [comment]
After looking into this, it seems it was just a result of network latency and it does seem to work.
