### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by falnyr** [rkoval/alfred-aws-console-services-workflow#55]
Hi @rkoval,

I must say I love this tool and I use it every day. I'd love to add a few contributions, but I'm wondering whether you're still actively maintaining the project. The latest update was in August 2022, and there are two Pull Requests open (#53 and #54).

What's the future for this project?

Thanks

**Comment by rkoval** [comment]
hey @falnyr - this project is very much alive! i just cleaned up the outstanding PRs and created a new release. sorry - it's been a busy fall/winter!!

i would definitely welcome contributions! what did you have in mind?

**Comment by rkoval** [comment]
sidenote: did the workflow prompt you that there was a new release available? i am trying to verify my fix for [this](https://github.com/rkoval/alfred-aws-console-services-workflow/issues/50#issuecomment-1097479268) from someone who isn't me 😅

**Comment by falnyr** [comment]
Hey @rkoval, great to hear project is alive! I did get a prompt in Alfred but I'm getting issues now with bad CPU type:

```
[17:25:57.932] Logging Started...
[17:26:00.248] AWS Console Services[Script Filter] Queuing argument ''
[17:26:00.260] AWS Console Services[Script Filter] Script with argv '(null)' finished
[17:26:00.264] ERROR: AWS Console Services[Script Filter] Code 126: /bin/bash: ./alfred-aws-console-services-workflow: Bad CPU type in executable
```

let me come back to you

**Comment by rkoval** [comment]
@falnyr - whoops! can you try installing [5.2.1](https://github.com/rkoval/alfred-aws-console-services-workflow/releases/tag/v5.2.1) and let me know if you still see this issue? I recently got an arm64 macbook, and this was my first release creating on it. I had forgotten to make the underlying go binary cross-compatible, so I'm assuming you were on an Intel mac from 5.2.0 and this was your issue

**Comment by falnyr** [comment]
Hey @rkoval, yes, I'm on Intel MBP. Thanks for the fix, works great!
