### ISSUE TITLE
All `aws ec2` commands open view-source

### ISSUE THREAD

**Issue by JorisKok** [rkoval/alfred-aws-console-services-workflow#64]
All ec2 (`aws ec2`) commands are opened with view-source prepended. Not sure if this is a browser bug or something in this workflow.

For example:
`aws ec2 targetgroups` opens `view-source:https://eu-west-1.console.aws.amazon.com/ec2/home?region=eu-west-1#TargetGroups`

All other commands are fine, only the ec2 ones are affected. I'm using Firefox. I tried reinstalling the workflow using the latest release.

**Comment by rkoval** [comment]
hmmm... i'm not sure what the issue could be here. it kinda feels like this may be an issue on the configuration of firefox or something else within macOS? i have not run into this issue myself, and i haven't seen anyone else report it. i'm going to close this issue, as i don't think there's anything actionable on our end, but please let me know if you figure this out!
